"""Add cascade del on Members

Revision ID: 191b5c6d7f03
Revises: 8be416cb06b5
Create Date: 2025-08-10 02:06:17.952487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '191b5c6d7f03'
down_revision: Union[str, None] = '8be416cb06b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('members_user_id_fkey'), 'members', type_='foreignkey')
    op.create_foreign_key(None, 'members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'members', type_='foreignkey')
    op.create_foreign_key(op.f('members_user_id_fkey'), 'members', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
