"""Add status user

Revision ID: 1b6a78fce076
Revises: 4ff2d7ec0d29
Create Date: 2025-06-28 18:03:12.895904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b6a78fce076'
down_revision: Union[str, None] = '4ff2d7ec0d29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    userstatus = sa.Enum('active', 'pending', 'blocked', name='userstatus')
    userstatus.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', userstatus, nullable=False, server_default='pending'))
    op.alter_column('users', 'tg_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'tg_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('users', 'status')

    sa.Enum(name='userstatus').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
