"""Create priority and deadline from tasks

Revision ID: 6c0fb238f1ee
Revises: 099ba7cdae79
Create Date: 2025-07-17 16:49:16.037861

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6c0fb238f1ee"
down_revision: Union[str, None] = "099ba7cdae79"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    task_priority_enum = sa.Enum(
        "low",
        "default",
        "high",
        "very_high",
        name="task_priority_enum",
    )
    task_priority_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column(
            "priority",
            task_priority_enum,
            server_default="default",
            nullable=False,
        ),
    )
    op.add_column(
        "tasks", sa.Column("deadline", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_index(op.f("ix_tasks_project_id"), "tasks", ["project_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    task_priority_enum = sa.Enum(
        "low",
        "default",
        "high",
        "very_high",
        name="task_priority_enum",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tasks_project_id"), table_name="tasks")
    op.drop_column("tasks", "deadline")
    op.drop_column("tasks", "priority")
    task_priority_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
