"""add null for tg_id

Revision ID: 8be416cb06b5
Revises: f62772bc0fe1
Create Date: 2025-08-01 19:46:48.761579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8be416cb06b5'
down_revision: Union[str, None] = 'f62772bc0fe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('unique_constraint_task_member'), 'assignees', type_='unique')
    op.drop_constraint(op.f('unique_constraint_user_project'), 'members', type_='unique')
    op.alter_column('users', 'tg_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'tg_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.create_unique_constraint(op.f('unique_constraint_user_project'), 'members', ['user_id', 'project_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('unique_constraint_task_member'), 'assignees', ['member_id', 'task_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
