"""

Revision ID: ee0ae01107df
Revises: 6c0fb238f1ee
Create Date: 2025-07-18 00:28:42.802878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee0ae01107df'
down_revision: Union[str, None] = '6c0fb238f1ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_assignees_member_id'), 'assignees', ['member_id'], unique=False)
    op.create_index(op.f('ix_assignees_task_id'), 'assignees', ['task_id'], unique=False)
    op.drop_constraint(op.f('assignees_task_id_fkey'), 'assignees', type_='foreignkey')
    op.drop_constraint(op.f('assignees_member_id_fkey'), 'assignees', type_='foreignkey')
    op.create_foreign_key(None, 'assignees', 'members', ['member_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'assignees', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_members_project_id'), 'members', ['project_id'], unique=False)
    op.create_index(op.f('ix_members_user_id'), 'members', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_members_user_id'), table_name='members')
    op.drop_index(op.f('ix_members_project_id'), table_name='members')
    op.drop_constraint(None, 'assignees', type_='foreignkey')
    op.drop_constraint(None, 'assignees', type_='foreignkey')
    op.create_foreign_key(op.f('assignees_member_id_fkey'), 'assignees', 'members', ['member_id'], ['id'])
    op.create_foreign_key(op.f('assignees_task_id_fkey'), 'assignees', 'tasks', ['task_id'], ['id'])
    op.drop_index(op.f('ix_assignees_task_id'), table_name='assignees')
    op.drop_index(op.f('ix_assignees_member_id'), table_name='assignees')
    # ### end Alembic commands ###
