"""

Revision ID: f62772bc0fe1
Revises: 1e7254dd9f26
Create Date: 2025-07-19 16:06:36.273994

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f62772bc0fe1"
down_revision: Union[str, None] = "1e7254dd9f26"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_unique_constraint(
        "unique_constraint_user_project", "members", ["user_id", "project_id"]
    )
    op.create_unique_constraint(
        "unique_constraint_task_member", "assignees", ["member_id", "task_id"]
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_constraint_user_project", "members")
    op.drop_constraint("unique_constraint_task_member", "assigns")
    # ### end Alembic commands ###
